import {
  MatBadgeModule,
  MatSidenavModule,
  MatAutocompleteModule,
  MatButtonModule,
  MatCardModule,
  MatDialogModule,
  MatGridListModule,
  MatIconModule,
  MatInputModule,
  MatListModule,
  MatMenuModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatSliderModule,
  MatSnackBarModule,
  MatTooltipModule,
  MatSelectModule,
  MatTabsModule,
  MatTableModule,
  MatChipsModule,
  MatRadioModule,
  MatCheckboxModule,
  MatPaginatorModule,
  MatSortModule,
  // MatDatepickerModule,
  MatNativeDateModule,
} from '@angular/material';
import { NgModule } from '@angular/core';

import { MatDatepickerModule, MatMomentDateModule } from '@coachcare/datepicker';


@NgModule({
  imports: [
    MatBadgeModule,
    MatSidenavModule,
    MatButtonModule,
    MatMenuModule,
    MatIconModule,
    MatCardModule,
    MatSliderModule,
    MatProgressBarModule,
    MatAutocompleteModule,
    MatInputModule,
    MatGridListModule,
    MatSnackBarModule,
    MatProgressSpinnerModule,
    MatTooltipModule,
    MatListModule,
    MatDialogModule,
    MatSelectModule,
    MatTabsModule,
    MatTableModule,
    MatSortModule,
    MatChipsModule,
    MatRadioModule,
    MatCheckboxModule,
    MatPaginatorModule,
    MatDatepickerModule,
    MatMomentDateModule,
    MatNativeDateModule,
  ],
  exports: [
    MatSidenavModule,
    MatButtonModule,
    MatSortModule,
    MatMenuModule,
    MatIconModule,
    MatCardModule,
    MatSliderModule,
    MatProgressBarModule,
    MatAutocompleteModule,
    MatInputModule,
    MatGridListModule,
    MatSnackBarModule,
    MatProgressSpinnerModule,
    MatTooltipModule,
    MatListModule,
    MatDialogModule,
    MatSelectModule,
    MatTabsModule,
    MatTableModule,
    MatChipsModule,
    MatRadioModule,
    MatCheckboxModule,
    MatPaginatorModule,
    MatBadgeModule,
    MatDatepickerModule,
    MatMomentDateModule,
    MatNativeDateModule,
  ],
})

export class MaterialModule {
}
