#.travis.yml

sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - 8.9

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
  - set -e
  - npm install
  - npm install -g angular-cli-ghpages
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - npm run test
  - npm run e2e
  - npm run build

notifications:
  email:
    on_failure: change
    on_success: change
